apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: temp-team-a
  description: Temp Team A
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: divyanshigupta3295@gmail.com
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: divyanshigupta
spec:
  profile:
    # Intentional no displayName for testing
    email: divyanshigupta3295@gmail.com
  memberOf: [temp-team-a]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: its-mitesh-kumar
spec:
  profile:
    # Intentional no displayName for testing
    email: itsmiteshkumar98@gmail.com
  memberOf: [temp-team-a]
---
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: sanketpathak
spec:
  profile:
    # Intentional no displayName for testing
    email: sanketpathak95@gmail.com
  memberOf: [temp-team-a]
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nationalparks-py
  labels: 
    component: nationalparks-py
  annotations:
    github.com/project-slug: divyanshiGupta/nationalparks-py
    backstage.io/kubernetes-id: nationalparks-py
    janus-idp.io/tekton: nationalparks-py
    # backstage.io/kubernetes-namespace: div
spec:
  type: service
  lifecycle: unknown
  owner: temp-team-a
